#! /bin/sh

if ! [ "$TLADD_CLIENTPATH" ] || ! [ "$TLADD_SERVER" ] || ! [ "$TLADD_SERVERPATH" ] || ! [ "$TLADD_CACHEPATH" ]; then
 cat <<EOF
Please define the following environment variables to use synctla:
TLADD_CLIENTPATH     Path to where local archives are stored (e.g. ~/.arch-archives)
TLADD_CACHEPATH      Path to where remote archives are mirrored locally (e.g. ~/.arch-remote-archives)
TLADD_SERVER         Hostname of server (e.g. dev.example.com)
TLADD_SERVERPATH     Path to where archives are mirrored on the server (e.g. /home/archarchives)
You can optionally define the following too:
TLADD_SERVERVIEWARCH Path to ArchViews' home directory on server (e.g. /var/www/ArchView)
EOF
 exit 1
fi

WORKDIR="$(mktemp -d)"

echo "Getting current listings..."
ls $TLADD_CLIENTPATH | sort > "$WORKDIR/locals"
ssh $TLADD_SERVER "ls $TLADD_SERVERPATH | sort" > "$WORKDIR/remotes"
ls $TLADD_CACHEPATH | sort > "$WORKDIR/cached"

diff "$WORKDIR/remotes" "$WORKDIR/locals" | grep -e "^<" | sed -e "s+< ++g" > "$WORKDIR/remotes.nonlocal"
diff "$WORKDIR/remotes.nonlocal" "$WORKDIR/cached" | grep -e "^<" | sed -e "s+< ++g" > "$WORKDIR/remotes.uncached"
diff "$WORKDIR/locals" "$WORKDIR/remotes" | grep -e "^<" | sed -e "s+< ++g" > "$WORKDIR/locals.uncached"

if [ "$1" == "--dry-run" ]; then
 echo "Remote archives to mirror locally:"
 cat "$WORKDIR/remotes.uncached"
 echo
 echo "Local archives to mirror remotely:"
 cat "$WORKDIR/locals.uncached"
 exit 0
fi

echo "Mirroring remote archives locally..."
while read REMOTE; do
 tla register-archive $REMOTE-SOURCE sftp://$TLADD_SERVER$TLADD_SERVERPATH/$REMOTE
 tla make-archive --mirror-from $REMOTE-SOURCE $TLADD_CACHEPATH/$REMOTE
done < "$WORKDIR/remotes.uncached"

echo "Mirroring local archives remotely..."
while read LOCAL; do
 tla make-archive --mirror $LOCAL sftp://$TLADD_SERVER$TLADD_SERVERPATH/$LOCAL
 if  [ "$TLADD_SERVERVIEWARCH" ]; then
  ssh $TLADD_SERVER "HOME=\"$TLADD_SERVERVIEWARCH\" tla register-archive $LOCAL \"$TLADD_SERVERPATH/$LOCAL\""
 fi
done < "$WORKDIR/locals.uncached"

rm -rf "$WORKDIR"

echo "Mirroring archive contents..."
for ARCHIVE in $(ls $TLADD_CLIENTPATH; ls $TLADD_CACHEPATH); do
 tla archive-mirror $ARCHIVE;
done
